### ISSUE TITLE
Change webpa-url command line argument format to <http/https>://<server_dns_name>:<port>

### ISSUE THREAD

**Issue by shilpa24balaji** [Comcast/parodus#149]
Add secure flag to parodus as command line argument to switch between http or https

**Comment by sadhyama** [comment]
This is fixed as part of pull request https://github.com/Comcast/parodus/pull/152 and is merged.

**Comment by shilpa24balaji** [comment]
Remove secure flag, port command line arguments.
Use webpa-url to be the complete url, containing secure (http/https), domain name and port

**Comment by shilpa24balaji** [comment]
These changes are now merged to master
