### ISSUE TITLE
webpa messages and payloads

### ISSUE THREAD

**Issue by vpaulino** [Comcast/parodus#150]
Hello. 

My name is Vitor Paulino and I work at NOS Inovação and we at NOS Inovação are starting to explore this and others repositories regarding webpa protocol. 
To understand the messages payload that are sent and received by parodus, it would be great if there was any documentation regarding the use cases and the messages that are exchanged. Can you provide something so we can start working on this?

Best regards 
Vitor Paulino

**Comment by schmidtw** [comment]
Vitor,

We're in the process of moving the more cross cutting docs into https://github.com/comcast/xmidt and it's wiki.  Until then [wrp-c wiki](https://github.com/Comcast/wrp-c/wiki/Web-Routing-Protocol) is the best description of the payloads.

Best,
Wes
