### ISSUE TITLE
TLS negotiation error in parodus

### ISSUE THREAD

**Issue by ganeshprasads** [Comcast/parodus#167]
We are getting a TLS negotiation error from parodus when it's trying to connect to a local talaria server & need some support on resolving this.
- Parodus is running in a DEV XG1v3 & talaria runs from a local server.
- The local servers are not configured with any certificate so we added --force-ipv4 --secure-flag=http   parameters as parodus command line arguments to disable certificate negotiation & https. 
- Also Same error is encountered with and without the --ssl-cert-path argument.

Command:
/usr/bin/parodus --hw-mac=84E058575831 --webpa-ping-time=180 --webpa-interface-used= --webpa-url=192.168.30.105 --partner-id=comcast --webpa-backoff-max=9 --force-ipv4 --secure-flag=http --ssl-cert-path=/etc/ssl/certs/ca-certificates.crt

Parodus log:
`... pacexg1v3 "parodus"[16560]: /usr/bin/parodus: unrecognized option --secure-flag=http'`
`2018 Jan 30 10:01:25.582268 pacexg1v3 parodus[16560]: 180130-10:01:25.582199 mod=PARODUS, lvl=INFO] [tid=16560] PARODUS: nopoll_conn.c:795 Enabling certificate peer verification`
`2018 Jan 30 10:01:25.584535 pacexg1v3 parodus[16560]: 180130-10:01:25.584430 mod=PARODUS, lvl=ERROR] [tid=16560] PARODUS: nopoll_conn.c:1001 there was an error with the TLS negotiation, ssl error (code:1) : error:00000001:lib(0):func(0):reason(1)`
`2018 Jan 30 10:01:25.584703 pacexg1v3 parodus[16560]: 180130-10:01:25.584657 [mod=PARODUS, lvl=ERROR] [tid=16560] PARODUS: nopoll_conn.c:478 tls stack: error:1408F10B:lib(20):func(143):reason(267) (find reason(code) at openssl/ssl.h)`
`2018 Jan 30 10:01:25.584773 pacexg1v3 parodus[16560]: 180130-10:01:25.584734 [mod=PARODUS, lvl=ERROR] [tid=16560] PARODUS: nopoll_conn.c:493     details, run: openssl errstr 1408F10B`
`2018 Jan 30 10:01:25.584870 pacexg1v3 parodus[16560]: 180130-10:01:25.584831 [mod=PARODUS, lvl=ERROR] [tid=16560] PARODUS: nopoll_conn.c:498     noPoll id=2, socket: 4 (after testing errno: 0)`
`2018 Jan 30 10:01:25.585222 pacexg1v3 parodus[16560]: 180130-10:01:25.585170 [mod=PARODUS, lvl=ERROR] [tid=16560] PARODUS: Error connecting to server`
`2018 Jan 30 10:01:25.585277 pacexg1v3 parodus[16560]: 180130-10:01:25.585241 [mod=PARODUS, lvl=ERROR] [tid=16560] PARODUS: RDK-10037 - WebPA Connection Lost`

**Comment by shilpa24balaji** [comment]
@ganeshprasads Recently we changed the parodus command line arguments.
secure flag is not supported now. Instead this is added to webpa-url.
So webpa-url in your case should be webpa-url=http://192.168.30.105:<port>

**Comment by shilpa24balaji** [comment]
@ganeshprasads Please confirm the git tag of parodus that your are currently using for testing. I am guessing you are not using the latest parodus master.
getaddrinfo error is from nopoll because i think the server_Address is considered as complete URL instead of just DNS
[mod=PARODUS, lvl=INFO] [tid=15719] PARODUS: server_Address http://192.168.30.105:8080

We changed the command line arguments recently. If you are using old parodus git tag, then you may have to use "secure" argument instead of this new webpa-url format.

**Comment by shilpa24balaji** [comment]
@ganeshprasads are you still facing this issue? Provide us more details, if not please close this issue.

**Comment by vivekjayachandran** [comment]
Hi, @shilpa24balaji  am also getting this same kind of the previous message, could please share with me how to find parodus master?
