### ISSUE TITLE
Rename command line options for MTLS cert and Key

### ISSUE THREAD

**Issue by shilpa24balaji** [Comcast/parodus#290]
There is name conflict for these command line options

- /client-cert-path -MTLS client cert location to request auth token from MTLS HTTPS server for establishing secure connection [absolute path where client cert is present] (optional argument)

**Websocket MTLS options**

- /client-cert-path - Provide the client cert for establishing a mutual auth secure websocket connection

- /client-key-path - Provide the client cert key for establishing a mutual auth secure websocket connection

So, rename MTLS websocket connect client cert and key path to **mtls-client-cert-path** and **mtls-client-key-path**

**Comment by bill1600** [comment]
?I can't find cert-key-path in parodus, or ENABLE_MUTUAL_AUTH.


________________________________

**Comment by schmidtw** [comment]
This should be closed, right?

**Comment by shilpa24balaji** [comment]
Yes fixed as part of #291
