### ISSUE TITLE
about the problem that nopoll_conn_wait_for_status_until_connection_ready not found in the open source nopoll.

### ISSUE THREAD

**Issue by rock6958** [Comcast/parodus#296]
dear, 
the function "nopoll_conn_wait_for_status_until_connection_ready" can not be found in the formal release version nopoll-1.0.0.tar.gz. only can be found in the test unit code.
is the original function not be merged with parodus?

**Comment by shilpa24balaji** [comment]
@rock6958 ,
This nopoll function is merged in the newer https://github.com/Comcast/nopoll/releases/tag/1.0.1 release.
This nopoll 1.0.1 git tag is used in parodus CMake file in the latest parodus 1.0.2 release.
https://github.com/Comcast/parodus/releases/tag/1.0.2
