### ISSUE TITLE
Parodus not compiling on Ubuntu 12.04

### ISSUE THREAD

**Issue by nidhichadha1** [Comcast/parodus#74]
Hi Wes , 

We are trying to build webpa on Ubuntu but facing compilation issues with respect to clock_gettime symbol undefined reference . I have ensured that -lrt library in included . 
Just for FYI ; tools version which I am using 

Ubuntu                 12.04.5  64bit
Cmake                   3.7.2
Make                     3.81
Gcc                          4.6.3
G++                       4.6.3
and cunit framework installation for webpa ucnit framework based tests . 

time.h is already included along with required included  RT library .

Can you please confirm if this environment is enough for compilation or is there any missing dependency : 
Here are logs : 
/CMakeFiles/test_conn_interface.dir/__/src/mutex.c.o  -o test_conn_interface  -L/home/rajesh/WebPA/parodus/build/_install/lib  -L/home/rajesh/WebPA/parodus/build/_install/lib64 -Wl,-rpath,/home/rajesh/WebPA/parodus/build/_install/lib:/home/rajesh/WebPA/parodus/build/_install/lib64 -rdynamic -lcmocka -lgcov -lcunit -lwrp-c -lpthread -lm -lmsgpackc -lcjson -ltrower-base64 -lnopoll -lnanomsg -lrt -lcimplog 
/home/rajesh/WebPA/parodus/build/_install/lib/libcimplog.so: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make[2]: *** [tests/test_conn_interface] Error 1
make[2]: Leaving directory `/home/rajesh/WebPA/parodus/build'
make[1]: *** [tests/CMakeFiles/test_conn_interface.dir/all] Error 2
make[1]: Leaving directory `/home/rajesh/WebPA/parodus/build'
make: *** [all] Error 2

Regards
Nidhi

**Comment by shilpa24balaji** [comment]
Please use ubuntu 14.04.5 instead of 12.04.5 to solve these parodus build errors.

**Comment by schmidtw** [comment]
The simplest thing will be to upgrade as shilpa suggests.  I've pulled a docker image and am trying to re-create the issue that way, but it will take me some time to work through several other problems before I get to the one you want solved.

Not sure if this suggestion will help:
http://stackoverflow.com/questions/17150075/undefined-reference-to-clock-gettime-although-lrt-is-given

**Comment by nidhichadha1** [comment]
thanks .  we have 16.0 version , I assume it should be fine as 14.04 .

**Comment by shilpa24balaji** [comment]
Ya 16 should be fine, but we have not tested. The problem with clock error is the order of the -lrt linking in CMakeFile.txt It requires changes at many places and will lead to more errors. So better is use higher version ob ubuntu.

**Comment by nidhichadha1** [comment]
Thanks Wes and Shilpa .  we are still on ubuntu12.04 but  with proper linker flags issue is resolved on this version as well 

Issue here is NEEDED list of few libraries  . This is resulting in non linking of rt library for libcimplog  even if librt is present  .Overriding this option in linker flags solves this issue  on ubuntu12.04 
In old tools/version, linker only links with the libraries which are given in NEEDED section of the library.
If  --no-as-needed is passed as Linker flag , then all the libraries will be linked regardless of what is given in  NEEDED section

Regards
Nidhi

**Comment by schmidtw** [comment]
I just merged #75 with the `--no-as-needed` flag.  If this doesn't work for you, please send us a PR with a fix.  Thanks!

**Comment by nidhichadha1** [comment]
It works with our local --no-as-needed flag  . But will confirm with latest fetch also . 

Thanks Wes .
